export const hashTbStockFilter = {
  "Thông tin cơ bản": [
    { name: "Sàn niêm yết", key: "" },
    { name: "Watchlist", key: "" },
    { name: "Ngành nghề kinh doanh", key: "" },
  ],
  "Thông tin cổ đông": [
    { name: "Tỷ lệ sở hữu của nhà đầu tư nước ngoài", key: "" },
  ],
  "Thống kê giá": [
    { name: "Giá hiện tại", key: "" },
    { name: "Giá tăng vượt đỉnh", key: "" },
    { name: "Giá giảm thủng đáy", key: "" },
    { name: "Thay đổi giá hôm nay (%)", key: "" },
    { name: "Thay đổi giá 1 tuần (%)", key: "" },
    { name: "Thay đổi giá 1 tháng (%)", key: "" },
    { name: "Thay đổi giá 3 tháng (%)", key: "" },
    { name: "Thay đổi giá 6 tháng (%)", key: "" },
    { name: "Thay đổi giá 1 năm (%)", key: "" },
    { name: "Beta", key: "" },
  ],
  "Khối lượng giao dịch": [
    { name: "Khối lượng giao dịch (cp)", key: "" },
    { name: "Tỷ lệ khối lượng Mua chủ động/Bán chủ động", key: "" },
    { name: "Khối lượng khớp lệnh vượt TB các ngày giao dịch (%)", key: "" },
    { name: "Khối lượng trung bình (cp)", key: "" },
    { name: "Khối lượng nước ngoài mua ròng (cp)", key: "" },
    { name: "Giá trị nước ngoài mua ròng (tỷ đồng)", key: "" },
  ],
  "Tín hiệu đường trung bình (MA)": [
    { name: "Giá hiện tại cắt lên đường SMA", key: "" },
    { name: "Giá hiện tại cắt xuống đường SMA", key: "" },
    { name: "Giá hiện tại cắt lên đường EMA", key: "" },
    { name: "Giá hiện tại cắt xuống đường EMA", key: "" },
    { name: "SMA ngắn hạn cắt lên SMA dài hạn", key: "" },
    { name: "SMA ngắn hạn cắt xuống SMA dài hạn", key: "" },
  ],
  "Tín hiệu chỉ số sức mạnh tương đối (RSI)": [
    { name: "RSI(14) đi vào vùng quá mua", key: "" },
    { name: "RSI(14) thoát khỏi vùng quá mua", key: "" },
    { name: "RSI(14) đang ở vùng quá mua", key: "" },
    { name: "RSI(14) đi vào vùng quá bán", key: "" },
    { name: "RSI(14) thoát khỏi vùng quá bán", key: "" },
    { name: "RSI(14) đang ở vùng quá bán", key: "" },
  ],
  "Tín hiệu dải băng Bollinger (Bollinger Bands)": [
    { name: "Giá thoát ra ngoài biên trên Bollinger Band (20)", key: "" },
    { name: "Giá cắt xuống từ ngoài biên trên Bollinger Band (20)", key: "" },
    { name: "Giá đang ở ngoài biên trên Bollinger Band (20)", key: "" },
    { name: "Giá thoát ra ngoài biên dưới Bollinger Band (20)", key: "" },
    { name: "Giá cắt lên từ ngoài biên dưới Bollinger Band (20)", key: "" },
    { name: "Giá đang ở ngoài biên dưới Bollinger Band (20)", key: "" },
  ],
  "Tín hiệu MACD": [
    { name: "MACD cắt lên đường tín hiệu", key: "" },
    { name: "MACD đang ở trên đường tín hiệu", key: "" },
    { name: "MACD cắt xuống đường tín hiệu", key: "" },
    { name: "MACD đang ở dưới đường tín hiệu", key: "" },
    { name: "MACD cắt lên đường 0", key: "" },
    { name: "MACD đang ở trên đường 0", key: "" },
    { name: "MACD cắt xuống đường 0", key: "" },
    { name: "MACD đang ở dưới đường 0", key: "" },
  ],
  "Kết quả kinh doanh": [
    { name: "Doanh thu thuần 4 quý gần nhất (tỷ đồng)", key: "" },
    { name: "Lợi nhuận ròng 4 quý gần nhất (tỷ đồng)", key: "" },
    { name: "Tăng trưởng doanh thu quý gần nhất (% yoy)", key: "" },
    { name: "Tăng trưởng doanh thu quý gần nhất (% qoq)", key: "" },
    { name: "Tăng trưởng doanh thu 4 quý gần nhất (%)", key: "" },
    { name: "Tăng trưởng lợi nhuận quý gần nhất (% yoy)", key: "" },
    { name: "Tăng trưởng lợi nhuận quý gần nhất (% qoq)", key: "" },
    { name: "Tăng trưởng lợi nhuận 4 quý gần nhất (%)", key: "" },
  ],
  "Định giá": [
    { name: "EPS (đồng/cp)", key: "" },
    { name: "BVPS (đồng/cp)", key: "" },
    { name: "P/E (lần)", key: "" },
    { name: "P/S (lần)", key: "" },
    { name: "P/B (lần)", key: "" },
    { name: "Tăng trưởng EPS 4 quý gần nhất (%)", key: "" },
    { name: "Vốn hóa (tỷ đồng)", key: "" },
  ],
  "Khả năng sinh lợi": [
    { name: "Tỷ lệ lãi gộp quý gần nhất (%)", key: "" },
    { name: "Tỷ lệ lãi gộp 4 quý gần nhất (%)", key: "" },
    { name: "Tỷ lệ lãi ròng quý gần nhất (%)", key: "" },
    { name: "Tỷ lệ lãi ròng 4 quý gần nhất (%)", key: "" },
    { name: "Tỷ lệ EBIT quý gần nhất (%)", key: "" },
    { name: "Tỷ lệ EBIT 4 quý gần nhất (%)", key: "" },
  ],
  "Sức mạnh tài chính": [
    { name: "Thanh toán hiện hành", key: "" },
    { name: "Thanh toán nhanh", key: "" },
    { name: "Khả năng thanh toán lãi vay", key: "" },
    { name: "Nợ/Vốn chủ sở hữu", key: "" },
    { name: "Nợ trả lãi/Vốn chủ sở hữu", key: "" },
    { name: "Nợ/Tổng tài sản", key: "" },
    { name: "Nợ trả lãi/Tổng tài sản", key: "" },
  ],
  "Hiệu quả quản lý": [
    { name: "ROA (%)", key: "" },
    { name: "ROE (%)", key: "" },
  ],
  "Khả năng hoạt động": [
    { name: "Vòng quay tổng tài sản", key: "" },
    { name: "Vòng quay hàng tồn kho", key: "" },
    { name: "Vòng quay các khoản phải thu", key: "" },
    { name: "Vòng quay tài sản ngắn hạn", key: "" },
  ],
};
